install.packages("keras")
library(keras)
install_keras
install.packages("tensorflow")
library(tensorflow)
install.packages("reticulate")
library(reticulate)
install.packages("tfruns")
library(tfruns)
